


export default [
    'color',
    'background-color',
    'border-color',
    'outline-color',
    'background-position',
    'left',
    'right',
    'top',
    'bottom',
    'max-height',
    'min-height',
    'max-width',
    'min-width',
    'height',
    'width',
    'border-width',
    'margin',
    'padding',
    'outline-width',
    'outline-offset',
    'font-size',
    'line-height',
    'text-indent',
    'vertical-align',
    'border-spacing',
    'letter-spacing',
    'word-spacing',
    'opacity',
    'visibility',
    'z-index',
    'font-weight',
    'zoom',
    'text-shadow',
    'transform',
    'box-shadow',
    'clip',
    'gradient',
];